imports:
    - package-container
    - ../../vendor/opine/collection/config/containers/package-container.yml
    - ../../vendor/opine/route/config/containers/package-container.yml
    - ../../vendor/opine/form/config/containers/package-container.yml
    - ../../vendor/opine/language/config/containers/package-container.yml
    - ../../vendor/opine/build/config/containers/package-container.yml
    - ../../vendor/opine/config/config/containers/package-container.yml
    - ../../vendor/opine/bundle/config/containers/package-container.yml
    - ../../vendor/opine/field/config/containers/package-container.yml
    - ../../vendor/opine/container/config/containers/package-container.yml
    - ../../vendor/opine/layout/config/containers/package-container.yml
    - ../../vendor/opine/handlebars/config/containers/package-container.yml
    - ../../vendor/opine/db/config/containers/package-container.yml
    - ../../vendor/opine/http/config/containers/package-container.yml
    - ../../vendor/opine/person/config/containers/package-container.yml
    - ../../vendor/opine/queue/config/containers/package-container.yml
    - ../../vendor/opine/search/config/containers/package-container.yml
    - ../../vendor/opine/mail/config/containers/package-container.yml
    - ../../vendor/opine/uploadwrapper/config/containers/package-container.yml
    - ../../vendor/opine/imageresizer/config/containers/package-container.yml